config/routes.rb
Geonews::Application.routes.draw do

    put "/news/:id", to: 'news#update'
    get "/news", to: 'news#index'

    root to: 'static_pages#home'

    match '/lemmatizer',  to: 'static_pages#lemmatizer'
    match '/help',        to: 'static_pages#help'
    match '/about',       to: 'static_pages#about'
    match '/contact',     to: 'static_pages#contact'
    match '/normalize',   to: 'static_pages#normalize'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/nimnes/geonews">Geo News</a>
    by nimnes
  </small>
  <nav>
    <ul>
      <li><%= link_to "О проекте",   about_path %></li>
      <li><%= link_to "Контакты", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
    <div class="container">
        <%= link_to "geonews", root_path, id: "logo" %>
        <nav>
            <ul class="nav pull-right">
                <li><%= link_to "Главная",    root_path %></li>
                <li><%= link_to "Новости",    news_path %></li>
                <li><%= link_to "Лемматизатор", lemmatizer_path %></li>
                <li><%= link_to "Помощь",    help_path %></li>
            </ul>
        </nav>
    </div>
</div>
</header>

app/views/layouts/_news_entry.html.erb
<% @news.all(:order => "published_at desc").each_with_index do |entry, index| %>
<li>
	<h4><%= entry.name %> (<%= entry.id %>)</h4>
	<span class="content"><%= entry.summary %></span>
	<span class="timestamp"><%= time_ago_in_words(entry.published_at) %></span>
	<span class="pull-right">
      Теги:
      <a href="#" id="tags<%= entry.id %>" data-type="select2" data-value="<%= entry.tags %>"
         data-url="/news/<%= entry.id %>" data-id="<%= entry.id %>" data-emptytext="Нет"
         data-placement="right" data-original-title="Теги"><%= entry.tags  %></a>
	</span>
</li>

<script>
    $(document).ready(function() {
        jQuery.noConflict();
        $('#tags<%= entry.id %>').editable({
            ajaxOptions: {
                type: 'put',
                dataType: 'json'
            },
            select2: {
                tags: ['<%= entry.tags %>'],
                tokenSeparators: [",", " "]
            }
        });
    });
</script>

<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>Geonews</title>
  	<%= stylesheet_link_tag    'application', media: 'all' %>
  	<%= javascript_include_tag 'application'%>
  	<%= csrf_meta_tags %>
  	<%= render 'layouts/shim' %> 
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>Geonews</title>
  	<%= stylesheet_link_tag    "application", media: "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
  	<%= render 'layouts/shim' %> 
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container-fluid">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>